// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class Tblresult
{
    public Guid ResultId { get; set; }

    public Guid? KoiId { get; set; }

    public double? ResultScore { get; set; }

    public string Prize { get; set; }

    public Guid? CompId { get; set; }

    public bool? Status { get; set; }

    public virtual Tblcompetition Comp { get; set; }

    public virtual TblkoiFish Koi { get; set; }
}