// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class Tblcompetition
{
    public Guid CompId { get; set; }

    public Guid? CategoryId { get; set; }

    public string CompName { get; set; }

    public string CompDescription { get; set; }

    public string Location { get; set; }

    public string ImageUrl { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public bool? Status { get; set; }

    public virtual ICollection<TblcompetitionCategory> TblcompetitionCategories { get; set; } = new List<TblcompetitionCategory>();

    public virtual ICollection<Tblprediction> Tblpredictions { get; set; } = new List<Tblprediction>();

    public virtual ICollection<Tblregistration> Tblregistrations { get; set; } = new List<Tblregistration>();

    public virtual ICollection<Tblscore> Tblscores { get; set; } = new List<Tblscore>();

    public virtual ICollection<Tbltask> Tbltasks { get; set; } = new List<Tbltask>();
}