// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class TblcheckIn
{
    public Guid CheckInId { get; set; }

    public string ImageUrl { get; set; }

    public int? Status { get; set; }

    public Guid? RegistrationId { get; set; }

    public string Description { get; set; }

    public virtual Tblregistration Registration { get; set; }
}