// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class Tblcategory
{
    public string CategoryId { get; set; }

    public string CategoryName { get; set; }

    public int? MinSize { get; set; }

    public int? MinAge { get; set; }

    public string CategoryDescription { get; set; }

    public int? MaxSize { get; set; }

    public int? MaxAge { get; set; }

    public virtual ICollection<TblcompetitionCategory> TblcompetitionCategories { get; set; } = new List<TblcompetitionCategory>();
}