// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class TblcompetitionCategory
{
    public Guid CompetitionCategoryId { get; set; }

    public Guid? CompId { get; set; }

    public Guid? CategoryId { get; set; }

    public bool? Status { get; set; }

    public virtual Tblcategory Category { get; set; }

    public virtual Tblcompetition Comp { get; set; }
}