// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class TblnewsType
{
    public Guid NewsTypeId { get; set; }

    public string NewsTypeName { get; set; }

    public virtual ICollection<Tblnews> Tblnews { get; set; } = new List<Tblnews>();
}