// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class Tblnews
{
    public Guid NewsId { get; set; }

    public string NewsTypeId { get; set; }

    public Guid? UserId { get; set; }

    public DateOnly? NewsDate { get; set; }

    public bool? Status { get; set; }

    public string NewsDescription { get; set; }

    public string ImageUrl { get; set; }

    public virtual TblnewsType NewsType { get; set; }

    public virtual Tbluser User { get; set; }
}