// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class Tblpayment
{
    public Guid PaymentId { get; set; }

    public string OrderId { get; set; }

    public Guid? UserId { get; set; }

    public decimal? Amount { get; set; }

    public string Status { get; set; }

    public string TransactionId { get; set; }

    public DateOnly? PaymentDate { get; set; }

    public DateOnly? CreatedAt { get; set; }

    public virtual Tbluser User { get; set; }
}