// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class Tblrank
{
    public Guid RankId { get; set; }

    public double? TotalPrize { get; set; }

    public double? TotalCompetition { get; set; }

    public Guid? KoiId { get; set; }

    public Guid? UserId { get; set; }

    public bool? Status { get; set; }

    public virtual TblkoiFish Koi { get; set; }

    public virtual Tbluser User { get; set; }
}