// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class Tblregistration
{
    public Guid RegistrationId { get; set; }

    public Guid? KoiId { get; set; }

    public Guid? CompId { get; set; }

    public int? Status { get; set; }

    public string ImageUrl { get; set; }

    public virtual Tblcompetition Comp { get; set; }

    public virtual TblkoiFish Koi { get; set; }

    public virtual ICollection<TblcheckIn> TblcheckIns { get; set; } = new List<TblcheckIn>();
}