// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class Tblscore
{
    public Guid ScoreId { get; set; }

    public Guid? KoiId { get; set; }

    public Guid? CompId { get; set; }

    public Guid? UserId { get; set; }

    public double? ScoreShape { get; set; }

    public double? ScoreColor { get; set; }

    public double? ScorePattern { get; set; }

    public double? TotalScore { get; set; }

    public bool? Status { get; set; }

    public virtual Tblcompetition Comp { get; set; }

    public virtual TblkoiFish Koi { get; set; }

    public virtual Tbluser User { get; set; }
}