// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class Tblscore
{
    public string ScoreId { get; set; }

    public string KoiId { get; set; }

    public string CompId { get; set; }

    public string UserId { get; set; }

    public double? ScoreShape { get; set; }

    public double? ScoreColor { get; set; }

    public double? ScorePattern { get; set; }

    public double? TotalScore
    {
        get
        {
            return 0.5 * ScoreShape + 0.3 * ScoreColor + 0.2 * ScorePattern;
        }
    }

    public virtual Tblcompetition Comp { get; set; }

    public virtual TblkoiFish Koi { get; set; }

    public virtual Tbluser User { get; set; }
}