// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class Tbltask
{
    public Guid TaskId { get; set; }

    public string TaskName { get; set; }

    public Guid? UserId { get; set; }

    public Guid? CompId { get; set; }

    public string TaskDescription { get; set; }

    public DateOnly? Date { get; set; }

    public bool? Status { get; set; }

    public virtual Tblcompetition Comp { get; set; }

    public virtual Tbluser User { get; set; }
}