// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class Tblvariety
{
    public string VarietyId { get; set; }

    public string VarietyName { get; set; }

    public string Origin { get; set; }

    public string VarietyDescription { get; set; }

    public virtual ICollection<TblkoiFish> TblkoiFishes { get; set; } = new List<TblkoiFish>();
}