// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class Tblnews
{
    public string NewsId { get; set; }

    public string NewsTypeId { get; set; }

    public string UserId { get; set; }

    public DateOnly? Date { get; set; }

    public string Description { get; set; }

    public virtual TblnewsType NewsType { get; set; }

    public virtual Tbluser User { get; set; }
}