// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class Tblregistration
{
    public string RegistrationId { get; set; }

    public string KoiId { get; set; }

    public string CompId { get; set; }

    public int? Status { get; set; }

    public virtual Tblcompetition Comp { get; set; }

    public virtual TblkoiFish Koi { get; set; }
}