// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class Tblrole
{
    public string RoleId { get; set; }

    public string RoleName { get; set; }

    public string RoleDescription { get; set; }

    public int? Experience { get; set; }

    public virtual ICollection<Tbluser> Tblusers { get; set; } = new List<Tbluser>();
}