// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KSM.Repository.Models;

public partial class Tblresult
{
    public string ResultId { get; set; }

    public string KoiId { get; set; }

    public double? ResultScore { get; set; }

    public string Prize { get; set; }

    public virtual TblkoiFish Koi { get; set; }

    public virtual ICollection<TblkoiFish> TblkoiFishes { get; set; } = new List<TblkoiFish>();
}