// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace KSM.Repository.Models;

public partial class VietKoiExpoContext : DbContext
{
    public VietKoiExpoContext()
    {
    }

    public VietKoiExpoContext(DbContextOptions<VietKoiExpoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Tblcategory> Tblcategories { get; set; }

    public virtual DbSet<Tblcompetition> Tblcompetitions { get; set; }

    public virtual DbSet<TblkoiFish> TblkoiFishes { get; set; }

    public virtual DbSet<Tblnews> Tblnews { get; set; }

    public virtual DbSet<TblnewsType> TblnewsTypes { get; set; }

    public virtual DbSet<Tblprediction> Tblpredictions { get; set; }

    public virtual DbSet<Tblregistration> Tblregistrations { get; set; }

    public virtual DbSet<Tblresult> Tblresults { get; set; }

    public virtual DbSet<Tblrole> Tblroles { get; set; }

    public virtual DbSet<Tblscore> Tblscores { get; set; }

    public virtual DbSet<Tbluser> Tblusers { get; set; }

    public virtual DbSet<Tblvariety> Tblvarieties { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection"));

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Tblcategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__TBLCateg__19093A2B52086AFD");

            entity.ToTable("TBLCategory");

            entity.Property(e => e.CategoryId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("CategoryID");
            entity.Property(e => e.CategoryDescription)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Category_Description");
            entity.Property(e => e.CategoryName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Species)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Tblcompetition>(entity =>
        {
            entity.HasKey(e => e.CompId).HasName("PK__TBLCompe__AD362A76440479AC");

            entity.ToTable("TBLCompetition");

            entity.Property(e => e.CompId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("CompID");
            entity.Property(e => e.CategoryId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("CategoryID");
            entity.Property(e => e.CompDescription)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CompName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Location)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Category).WithMany(p => p.Tblcompetitions)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_TBLCompetition_CategoryID");
        });

        modelBuilder.Entity<TblkoiFish>(entity =>
        {
            entity.HasKey(e => e.KoiId).HasName("PK__TBLKoiFi__E03435B8EB5349B8");

            entity.ToTable("TBLKoiFish");

            entity.Property(e => e.KoiId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("KoiID");
            entity.Property(e => e.KoiName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ResultId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ResultID");
            entity.Property(e => e.UserId)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("UserID");
            entity.Property(e => e.VarietyId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("VarietyID");

            entity.HasOne(d => d.Result).WithMany(p => p.TblkoiFishes)
                .HasForeignKey(d => d.ResultId)
                .HasConstraintName("FK_TBLKoiFish_ResultID");

            entity.HasOne(d => d.User).WithMany(p => p.TblkoiFishes)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__TBLKoiFis__UserI__440B1D61");

            entity.HasOne(d => d.Variety).WithMany(p => p.TblkoiFishes)
                .HasForeignKey(d => d.VarietyId)
                .HasConstraintName("FK__TBLKoiFis__Varie__4316F928");
        });

        modelBuilder.Entity<Tblnews>(entity =>
        {
            entity.HasKey(e => e.NewsId).HasName("PK__TBLNews__954EBDD37CF78BE2");

            entity.ToTable("TBLNews");

            entity.Property(e => e.NewsId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NewsID");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.NewsTypeId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NewsTypeID");
            entity.Property(e => e.UserId)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("UserID");

            entity.HasOne(d => d.NewsType).WithMany(p => p.Tblnews)
                .HasForeignKey(d => d.NewsTypeId)
                .HasConstraintName("FK__TBLNews__NewsTyp__3D5E1FD2");

            entity.HasOne(d => d.User).WithMany(p => p.Tblnews)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__TBLNews__UserID__3E52440B");
        });

        modelBuilder.Entity<TblnewsType>(entity =>
        {
            entity.HasKey(e => e.NewsTypeId).HasName("PK__TBLNewsT__9013FE2ACA21C9D8");

            entity.ToTable("TBLNewsType");

            entity.Property(e => e.NewsTypeId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NewsTypeID");
        });

        modelBuilder.Entity<Tblprediction>(entity =>
        {
            entity.HasKey(e => e.PredictionId).HasName("PK__TBLPredi__BAE4C140F22BFFF1");

            entity.ToTable("TBLPrediction");

            entity.Property(e => e.PredictionId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PredictionID");
            entity.Property(e => e.CompId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("CompID");
            entity.Property(e => e.KoiId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("KoiID");

            entity.HasOne(d => d.Comp).WithMany(p => p.Tblpredictions)
                .HasForeignKey(d => d.CompId)
                .HasConstraintName("FK__TBLPredic__CompI__5441852A");

            entity.HasOne(d => d.Koi).WithMany(p => p.Tblpredictions)
                .HasForeignKey(d => d.KoiId)
                .HasConstraintName("FK__TBLPredic__KoiID__534D60F1");
        });

        modelBuilder.Entity<Tblregistration>(entity =>
        {
            entity.HasKey(e => e.RegistrationId).HasName("PK__TBLRegis__6EF588307C33BC25");

            entity.ToTable("TBLRegistration");

            entity.Property(e => e.RegistrationId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("RegistrationID");
            entity.Property(e => e.CompId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("CompID");
            entity.Property(e => e.KoiId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("KoiID");

            entity.HasOne(d => d.Comp).WithMany(p => p.Tblregistrations)
                .HasForeignKey(d => d.CompId)
                .HasConstraintName("FK__TBLRegist__CompI__4D94879B");

            entity.HasOne(d => d.Koi).WithMany(p => p.Tblregistrations)
                .HasForeignKey(d => d.KoiId)
                .HasConstraintName("FK__TBLRegist__KoiID__4CA06362");
        });

        modelBuilder.Entity<Tblresult>(entity =>
        {
            entity.HasKey(e => e.ResultId).HasName("PK__TBLResul__976902288558C5CB");

            entity.ToTable("TBLResult");

            entity.Property(e => e.ResultId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ResultID");
            entity.Property(e => e.KoiId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("KoiID");
            entity.Property(e => e.Prize)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.Koi).WithMany(p => p.Tblresults)
                .HasForeignKey(d => d.KoiId)
                .HasConstraintName("FK__TBLResult__KoiID__46E78A0C");
        });

        modelBuilder.Entity<Tblrole>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__TBLRole__8AFACE3AC354D568");

            entity.ToTable("TBLRole");

            entity.Property(e => e.RoleId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("RoleID");
            entity.Property(e => e.RoleDescription)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("Role_Description");
            entity.Property(e => e.RoleName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Tblscore>(entity =>
        {
            entity.HasKey(e => e.ScoreId).HasName("PK__TBLScore__7DD229F17EB024A8");

            entity.ToTable("TBLScore");

            entity.Property(e => e.ScoreId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ScoreID");
            entity.Property(e => e.CompId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("CompID");
            entity.Property(e => e.KoiId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("KoiID");
            entity.Property(e => e.UserId)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("UserID");

            entity.HasOne(d => d.Comp).WithMany(p => p.Tblscores)
                .HasForeignKey(d => d.CompId)
                .HasConstraintName("FK__TBLScore__CompID__5812160E");

            entity.HasOne(d => d.Koi).WithMany(p => p.Tblscores)
                .HasForeignKey(d => d.KoiId)
                .HasConstraintName("FK__TBLScore__KoiID__571DF1D5");

            entity.HasOne(d => d.User).WithMany(p => p.Tblscores)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__TBLScore__UserID__59063A47");
        });

        modelBuilder.Entity<Tbluser>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__TBLUser__1788CCAC74CB75EC");

            entity.ToTable("TBLUser");

            entity.Property(e => e.UserId)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("UserID");
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FullName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RoleId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("RoleID");

            entity.HasOne(d => d.Role).WithMany(p => p.Tblusers)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK__TBLUser__RoleID__3A81B327");
        });

        modelBuilder.Entity<Tblvariety>(entity =>
        {
            entity.HasKey(e => e.VarietyId).HasName("PK__TBLVarie__08E3A0485F80A988");

            entity.ToTable("TBLVariety");

            entity.Property(e => e.VarietyId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("VarietyID");
            entity.Property(e => e.Origin)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.VarietyDescription)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Variety_Description");
            entity.Property(e => e.VarietyName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}